server:
  port: 8023
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.qq.com
    port: 465
    username: ENC(2a34EAfYxma1BXFO4dZRCP3SdTUyz7+qyKmZ7QEKJrA=)
    password: ENC(qaB+zE7L5VObM1hK1YtcBMT1+brMcY0w8FeBpU/PiZo=)
#    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  # redis
  redis:
    database: 11
    host: localhost
    port: 6379
  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000 #ms
  # elasticsearch
  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 127.0.0.1:9300

# 加密参数
jasypt:
  encryptor:
    password: test

# 配置sql打印日志
logging:
  level:
    com.tassel.mapper:
      debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tassel.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

community:
  path:
    domain: http://localhost:8023
    upload: E:\Documents\Projects\Community\upload
